### ISSUE TITLE
use of prototype methods for better CPU/Mem usage?

### ISSUE THREAD

**Issue by trusktr** [felixmariotto/three-mesh-ui#18]
https://github.com/felixmariotto/three-mesh-ui/blob/1b5a699840219261bc750fd49f7c7a681d601895/src/components/core/BoxComponent.js#L20

That creates the method anew for each instance. Example: if there's 5 methods in a class, and 5 instances, that'll create 5x5 function instances.

It's nothing big to worry about, just sticking this here so we can check it out later. (But you are in quite the envious hack mode :smile: so I wouldn't be surprised if you got to it before I could swing back!)

Side question: have you considered using `class`? If you decided not to, is it for old browser support?

**Comment by trusktr** [comment]
I haven't gotten back around to attempt to contribute anything yet, but this sort of change (if you want it) is also something I could work on to start getting familiar with things.

**Comment by felixmariotto** [comment]
You're right it was not very smart to do it like this. Yes if you want you can do this !

As for `class`, I don't know, I don't really like this... I always prefer explicit code, so I've been using `Object.create()`, which doesn't hide prototypal inheritance behind syntactic suggar.

All in all it's the same isn't it ?

**Comment by felixmariotto** [comment]
@trusktr Sorry I did it... I'm working on the project every day so it moves fast, and as I'm doing a big cleanup at the moment it made no sense not to do it. I appreciate your willingness to work on it nonetheless !

Also I updated the architecture.
I noticed that it was going toward an entangled inheritance tree... So I decided to use composition instead of inheritance to construct a component with the various modules it needs. I realised it was necessary when I made [InlineBlock](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/InlineBlock.js), which must behave both like a box and like an inline component. Positioning that in an inheritance tree was hacky and I feared it would not but sustainable on the long run.
