### ISSUE TITLE
Raycasting Blocks for Buttons

### ISSUE THREAD

**Issue by kalegd** [felixmariotto/three-mesh-ui#3]
In the example for buttons there is some custom code in VRControl to handle Raycasting. I think it might make sense to make a utility function for raycasting the UI as part of this project's source code. That or restructure some things to make it easier to use THREE.Raycaster. Thoughts?

**Comment by felixmariotto** [comment]
I agree that it feels somewhat clumsy now, but so far I've not found a better way so I would use some help figuring this out.

Here are the things I should mention : 
- Block objects are not THREE.Object3Ds, and cannot be (they have their own chain of prototypes), therefore they cannot be passed as is to Raycaster.intersectObjects, we have to map the Blocks array to extract the Block.frameContainer properties, that's what happens here : 
https://github.com/felixmariotto/three-mesh-ui/blob/a1a09d688b7fec6b205199add856960fc7a66841/examples/js/utils/VRControl.js#L197-L209
Here are the solutions I can think of to hide that from the user : a function that takes a raycaster and an array of components (that's what intersectUI is basically, but it could have its own module and call Raycaster.intersectObjects directly) -- or, an instance of THREE.Raycaster that i would modify and that the user could use to directly Raycaster.intersectObjects(components). This would oblige the user to manage two raycasters though, and to perform this kind of operations twice : 
https://github.com/felixmariotto/three-mesh-ui/blob/a1a09d688b7fec6b205199add856960fc7a66841/examples/js/utils/VRControl.js#L249-L252
Besides, the philosophy of this lib is to be as non-intrusive as possible (there is enough VR frameworks out there), so while taking things out of VRControl may follow this rule, obliging the user to use a custom Raycaster is maybe not the best alternative.     
     
- All the part to create controllers pointing helpers is chunky but necessary (the rays and dots), so I would like to keep it in a separate module "VRControl". Howerver we can imagine that the object returned by VRControl would have a "controllers" property, and this operations would be done in the example module : 
https://github.com/felixmariotto/three-mesh-ui/blob/a1a09d688b7fec6b205199add856960fc7a66841/examples/js/utils/VRControl.js#L245-L296

I'm determined to make this lib user-friendly, let me know what you think.

**Comment by kalegd** [comment]
I spent some time playing with things today. I changed my mind and no longer believe raycasting should be part of the library, and that the way raycasting currently needs to done 100% makes sense and that the example code itself is fine. However, for the sake of it being an example I think that all raycasting code should done in interactive_button.js as that directly pertains to understanding how buttons work in this library

I'm personally a fan of examples having all code directly relating to what is being demo'd in one file. So if you agree and it's fine with you, I'll play with it a bit more to decouple the raycasting code from VRControl.js and throw up a pull request?

**Comment by kalegd** [comment]
Also, given how raycasting buttons usually needs the frameContainer linked to the actual Block Object, I think it would make sense for frameContainer and all frames associated with a block to already have a parameter that references the block. Kind of like how all Object3Ds have a parent that references their parent. Thoughts?

Could be something like this in Block.js

```javascript
function Block( options ) {
    ...
    const frameContainer = new Object3D();
    frameContainer.name = "MeshUI-FrameContainer"
    frameContainer.block = block;
    ...
    block.updateLayout = function UpdateLayout() {
        ...
        frame.renderOrder = block.getParentsNumber();
        frame.block = block;
```
This way we remove the need for a findOwner function and the mapping of block to owner. If most people will be adding some way to manage the relationships to the block like in the example might as well have that information ready from the get go

**Comment by felixmariotto** [comment]
> I'm personally a fan of examples having all code directly relating to what is being demo'd in one file. So if you agree and it's fine with you, I'll play with it a bit more to decouple the raycasting code from VRControl.js and throw up a pull request?

I agree and I'm totally up for a PR, I'm actually quite busy implementing MSDF fonts to the lib, so it helps me a lot, thank you.

> I think it would make sense for frameContainer and all frames associated with a block to already have a parameter that references the block. Kind of like how all Object3Ds have a parent that references their parent.

It makes sense, go ahead. 👍    
But I would prefer something more general than ".block", because eventually it will be possible to raycast other things than Blocks, like Texts for instance, and the same raycasting functions should work for Blocks and Texts. Something like "uiComponent" ?

**Comment by trusktr** [comment]
Pardon if I missed any conversation about this, as I'm new here, but why not embrace the Three.js scene graph by having things like `Block` extend from `Object3D`?

I think that unless the plan is to eventually support other back ends (f.e. PlayCanvas or Babylon), then it will be cleaner to extend the existing classes because it makes them interoperable with existing Three.js scenes in ways people are already familiar with.

F.e., existing Three.js users would naturally understand:

```js
const block = new Block(options)
block.position.set(20, 30, 40)
```

in the same pattern as with everything else that extends from `Object3D`.

Plus, then this makes it easier to interop with things like Raycaster and other things included with Three.js.

**Comment by trusktr** [comment]
I haven't looked at all the example code yet (going through it right now), but [this example](https://three-mesh-ui.herokuapp.com/#interactive_button) does show usage with a mouse. Cool!

**Comment by trusktr** [comment]
Ah, I see, `Block` has its own methods like `appendChild` to add content; it has its own tree (with DOM-like).

The custom tree can then make the internal Three.js tree in a structure that may not match the UI tree.

I need to learn more...

**Comment by felixmariotto** [comment]
Yes every component in the lib has its own tree, and ultimately inherit from MeshUIComponent, which is basically the property getter/setter. We can imagine that MeshUIComponent would inherit from Object3D though. Just for understanding if it's worth the refactoring, can we try listing what would the benefits be ?

What I can think of : 
- THREE.Raycaster.intersectObjects([ Block, Block.. ])
- Block.position.set()
- Block.scale.set()
- Block.visible = true/false

The ability to transform the Blocks with Object3D methods is limited, though, because it would break the layout chain. For instance, if you have a parent Block with no defined size but padding, it will size according to the children size and add padding. Of course if you change the scale of the children, it will look weird... You really only want to transform the root Block, and in the examples that's what I do by adding the root Block to an Object3D, that I transform. I do realise though that it may be more user-friendly to transform the root Block directly.

Maybe it's worth it.

**Comment by trusktr** [comment]
Yeah, that's mainly it, is just similarity/interop with existing patterns.

> THREE.Raycaster.intersectObjects([ Block, Block.. ])

Currently we can write that as

```js
THREE.Raycaster.intersectObjects([ Block, Block.. ].map(b => b.threeOBJ))
```

But then we may also need to map back from the Three objects to the Blocks after the raycast. (I recommend not using `Object3D.userData` for this, but a `Map`).

```js
import {threeToBlockMap} from 'three-mesh-ui'

// given
let array = [ Block.threeOBJ, Block.threeOBJ ]

// we can get the Blocks
const block = threeToBlockMap.get(array[0])
```

This would be compatible with [lume/glas](https://github.com/lume/glas) once that is ready (port of Three.js to AssemblyScript (a TypeScript to WebAssembly)), because AssemblyScript supports only the strict type features of TypeScript and for example doesn't support un-typed objects like `userData`.

**Comment by felixmariotto** [comment]
I'm closing this because it has been addressed by release 2.1.0

Raycasting is now done in the examples page, and the components inherit from THREE.Object3D

**Comment by trusktr** [comment]
Wow, you are on a roll! I love it when that happens on my projects too. I see the `isUI` check to make it work while inheriting from Object3D. Looks good.

**Comment by felixmariotto** [comment]
It was really a good decision, things are much more clear now that components are Object3Ds !
