### ISSUE TITLE
BackgroundColor and BackgroundTexture

### ISSUE THREAD

**Issue by David-ImmersionTools** [felixmariotto/three-mesh-ui#38]
Hi,
I just update the three-mesh-ui in my project, and the background texture doesn't change color then i set the background color attribute. Insted it change the over part of the background.

```
this.background.set({
   backgroundColor: new THREE.Color('#FF0000'),
   backgroundTexture:  this.textureBack,
   opacity: 1,
});

this.object.set({
    backgroundColor: new THREE.Color('#00FF00'),
    backgroundTexture:  this.texture,
    opacity: 1,
})
```
![icon](https://user-images.githubusercontent.com/44195807/86580749-68e7e080-bf7f-11ea-9b2b-b87d1c31a852.png)

**Comment by felixmariotto** [comment]
Hi,

Yes, that's because the background shader picks either your defined background color or the texture color depending on the texture alpha on the fragment : 
https://github.com/felixmariotto/three-mesh-ui/blob/25a93326cc60f1374c2b00507f31d9b7c82b7275/src/components/core/MaterialManager.js#L263-L267

It's a shortcoming, I've been wanting to blend the passed texture with the passed backgroundColor and backgroundOpacity, but there is a design issue that kept me from doing so : 
[The default backgroundColor is grey](https://github.com/felixmariotto/three-mesh-ui/blob/25a93326cc60f1374c2b00507f31d9b7c82b7275/src/utils/Defaults.js#L21), which is good for most cases when there is no texture. But when there is a texture, the color should be white by default, or there will be unintended grey blending, that the user might not understand...

The obvious workaround would be to update this generic getter : 
https://github.com/felixmariotto/three-mesh-ui/blob/25a93326cc60f1374c2b00507f31d9b7c82b7275/src/components/core/MeshUIComponent.js#L165-L167

into something more complicated, which, when looking for the default backgroundColor, first check if a backgroundTexture exists, and if so returns white. IMO this is clumsy, but I can't think of anything else.

I'm open for suggestion for anything better, and anyway I will add this color blending feature.
I can't tomorrow, but I can the day after.

**Comment by felixmariotto** [comment]
I've actually had the time to do it today. 

The feature was added with [v4.3.0](https://github.com/felixmariotto/three-mesh-ui/releases/tag/v4.3.0).
See live example [here](https://three-mesh-ui.herokuapp.com/#inline_block).

As your request seems addressed I'm closing this issue, but feel free to reach out.
