### ISSUE TITLE
Text scroll 

### ISSUE THREAD

**Issue by mhmtsrfglu** [felixmariotto/three-mesh-ui#57]
I need to scroll text when overflow. Is it possible ?

Thanks Mehmet

**Comment by felixmariotto** [comment]
Hi @mhmtsrfglu,

I guess you have seen [this example](https://three-mesh-ui.herokuapp.com/#hidden_overflow). To scroll the child panel, you can just move it like any three.js object : `child.position.y -= 0.1`. The logic to "grab" the child and compute the distance to scroll is left to you, since three-mesh-ui does not provide VR controls. I understand that this can be a bit complex, so I can make a new example to show how to do it, but I'm celebrating Christmas at the moment so I will do it next week.

**Comment by mhmtsrfglu** [comment]
Yes, I saw this example, on the other hand I am waiting for new example. Mary Christmas!

**Comment by r03ert0** [comment]
hello! I'm trying to do text scrolling, based on the `hiddenOverflow` example. In that example, the `position.y` of the textContainer is set to a different value every time in the render loop. However, if just set the position once (for a specific scroll amount), it gets reset when the loop reaches `ThreeMeshUI.update()`. Is there a way of preventing this? or I need to always enforce the new `position.y` after update in the loop?

**Comment by felixmariotto** [comment]
@r03ert0 Sorry for the late answer.

In [this fiddle](https://jsfiddle.net/felixmariotto/2kLetnzu/) I move a block once and it doesn't get updated automatically afterwards.

Three-mesh-ui components extend `three.Object3D` and use `Object3D.position` to layout the components, so if you do something that triggers a layout update, your manual setting of `Object3D.position` will be overridden. However, I don't think a layout update should happen every frame, typically it only happens once, on the frame in which the components were created.

Three-mesh-ui keeps track of the components that need an update, in order to only update what is needed. What registers a specific component for an update is [`MeshUIComponent.setState( state )`](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#meshuicomponentsetstate-state-) or [`MeshUIComponent.set( options )`](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#meshuicomponentset-options-). If your component gets updated every frame, it means that you are calling one of these two functions every frame, which is not advised performance-wise.

**Comment by r03ert0** [comment]
thank you very much!
