### ISSUE TITLE
How to set double-sided display?

### ISSUE THREAD

**Issue by WREQI** [felixmariotto/three-mesh-ui#65]
How to set double-sided display?

**Comment by felixmariotto** [comment]
What do you mean by that ?
Do you want text to appear on both front side and back side ?
Or do you only want the back of the panels to be opaque ?
I've posted a fiddle in your previous issue on how you could do it : https://jsfiddle.net/felixmariotto/xbs6mcaq/

**Comment by WREQI** [comment]
![image](https://user-images.githubusercontent.com/35467304/113694640-97f3d400-9702-11eb-9090-ea2a44035e16.png)
Yes, I saw that you created it twice, can't you set side=2 like the material? How to create it once and display it as 2

**Comment by WREQI** [comment]
I want to display Chinese, what should I do?

**Comment by felixmariotto** [comment]
> Yes, I saw that you created it twice, can't you set side=2 like the material? How to create it once and display it as 2

You can't do this with the lib, anyway the letters would be mirrored so I don't think it would be readable ?

> I want to display Chinese, what should I do?

[create your own font file](https://github.com/felixmariotto/three-mesh-ui/wiki/Creating-your-own-fonts) to include chinese characters. As for the vertical-direction reading, it's not available in the lib, but I'm open for PRs. In case you want to implement it, I suggest you add a `textOrientation` attribute. It would be checked [here](https://github.com/felixmariotto/three-mesh-ui/blob/91453152cb72a0a9a22536b46926024254d16771/src/content/MSDFText.js#L61-L81) in order to know in what direction to translate the characters. [InlineManager](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/InlineManager.js) is responsible for computing the offset, and will need to be tweaked too. I suggest you read [this](https://github.com/felixmariotto/three-mesh-ui/wiki/Roadmap-&-Contributions) before working on a PR.

**Comment by felixmariotto** [comment]
closing this because no followup
