### ISSUE TITLE
Font size seems to be off by a factor of 1.5 (approximately)

### ISSUE THREAD

**Issue by trusktr** [felixmariotto/three-mesh-ui#7]
It seems font sizing is off by (approximately, based on my eye) a factor of ~~two~~ 1.5.

I made an example here:

https://codepen.io/trusktr/pen/44f06fe6d8ef732770643b5707b7bd1a

In that example, see how the numbers (`BOX_SIZE`, `FONT_SIZE`, etc) map to both CSS and WebGL. Everything matches up, except the WebGL font looks about twice as big.

Question: can a font have its own intrinsic size, which would cause the font to look bigger than another font even if they have the same specified font size?

**Comment by trusktr** [comment]
Actually the factor seems to be about `1.5`. Here's a demo with the factor applied:

https://codepen.io/trusktr/pen/d7b94cc7826b969a8c6e2879d3d48c6c

**Comment by trusktr** [comment]
Super nice lib by the way. Having fun with it! :)

**Comment by felixmariotto** [comment]
Mh yes this should match. Also it's worth noting that MSDFText is off by another factor, ultimately all the Text class should match in scale with CSS.

I'm planning on adding a third Text class for fast-updating text shortly, so it's maybe better to wait for it to fix this, what do you think ?

In any event I added this to the [roadmap](https://github.com/felixmariotto/three-mesh-ui/wiki/Roadmap)

**Comment by trusktr** [comment]
>  so it's maybe better to wait for it to fix this, what do you think ?

Yeah, it is tangential and can be adjusted later, I can live with a hard-coded multiplier number. :)

**Comment by felixmariotto** [comment]
I removed the geometry text entirely as I realised that the library needs to control component's materials in order to do clipping for [this](https://three-mesh-ui.herokuapp.com/#hidden_overflow).

So now the question of discrepancy between the geometry and MSDF text makes no sense anymore.

I kept the architecture ready to welcome a new type of text though, the the issue may rise again.

**Comment by trusktr** [comment]
I prefer GeometryText over MSDF I think. Now there's only MSDF right? Why not keep both, and document that with GeometryText there is no overflow clipping.

There can also be an alternative render mode, where text is rendered to a Texture or WebGLRenderTarget (less performance, but means we can clip GeometryText).

**Comment by felixmariotto** [comment]
> Why not keep both, and document that with GeometryText there is no overflow clipping.

I'm not a fan of this, people don't read the doc so thoroughly... All types of texts should ideally have the same API and support the same feature, or the lib usage will be too complicated. As you said, it's possible to support clipping for geometry text anyway, the issue is more about supporting custom shaders.

> Also, what about a technique of dropping certain pixels (either in the fragment shader, or in a post processing effect) to do clipping?

Yes I've thought about it too... It would fix another issue :   
currently the clipping does not follow rounded edges. Dropping pixels in the shader according to a roundedEdgeRadius uniform would fix this.

But the problem is the same : How do we let the users add their own shaders for the texts, given that the lib is creating and managing its own ShaderMaterials ? I'm quite new at shaders, so I'm not aware of all the possibilities.

> troika's TextMesh that uses GlyphGeometry

Currently the library has no dependency other than three.js, and I think it's great. I want this project to be easy to maintain, it will help it lasting long. Besides, troika is an alternative solution to three-mesh-ui ( not exactly the same, more "framework-that-does-everything" than "minimalist three.js plugin", but still ), therefore it's not a good strategic decision to depend on it.

**Comment by trusktr** [comment]
What if TextMesh and GlyphGeometry were in a separate package?
