### ISSUE TITLE
Block Backfaces

### ISSUE THREAD

**Issue by JoeCoppola-HIA** [felixmariotto/three-mesh-ui#72]
A neat feature would be block backfaces. Would add to the 3D effect, as opposed to the UI disappearing when looking at it from behind. 

I could see it being an optional attribute that is enabled via the constructor and set API. If enabled, the block would create a second frame like object and rotate it to be opposite of the main frame, to act as a simple backface. No need to mirror the content of the main frame, rather just be a solid or transparent color. 

This can be done outside of the library, but I figured I'd see what thoughts are on supporting this idea.

Cheers,

Joe

**Comment by JoeCoppola-HIA** [comment]
Sort of an idea of what it could look like.


https://user-images.githubusercontent.com/83366171/121239422-d589f000-c85e-11eb-871c-6433c9b3d173.mp4

**Comment by felixmariotto** [comment]
Hi @JoeCoppola-HIA 

I agree that would be cool.. But there is a technical issue here. When the root Block is transparent, look what happen : 


https://user-images.githubusercontent.com/46470486/121250171-b2cefa00-c8a5-11eb-8b19-0048fe125368.mp4

I actually set its opacity to 0.1 to make it more clear, but with 0 it's even more terrible.

**Why is this happening ?**
 Because three-mesh-ui manually set the renderOrder of its components [here](https://github.com/felixmariotto/three-mesh-ui/blob/fd5e85070d9033818d8f6f9d934bbf86e8ca8f53/src/components/Block.js#L98).

**Why do we manually sort ?**
To avoid Z-fighting. Three-mesh-ui components are generally very packed together and letting three sort automatically would lead to Z-fighting.

I'm afraid this limitation will be difficult to work around... I would suggest using onAfterUpdate to set `Block.frame.material.side` like in [this fiddle](https://jsfiddle.net/felixmariotto/a5m72rq8/) ( looks like this method turns useful ! )

**Comment by JoeCoppola-HIA** [comment]
Ahh that would explain the issues I saw on this example. That fiddle however is a very solid solution, and likely more performant than creating a whole new Frame. Thanks for the input! Closing as the fiddle is exactly what I need.

**Comment by felixmariotto** [comment]
@JoeCoppola-HIA Just happened to notice a bug with `onAfterUpdate` while doing the fiddle... follow-up here : #73
