### ISSUE TITLE
hiddenOverflow doesn't seem to always be respected

### ISSUE THREAD

**Issue by dmliao** [felixmariotto/three-mesh-ui#74]
Hi there. I've been playing around with this library, and have generally been puzzled as to when `hiddenOverflow` can be used to hide text and block content; it works when I pull the example locally, but certain layouts have caused it to stop working, such as the one I made here: https://jsfiddle.net/rw2cha3f/. 

Is there a way to make something like this respect `hiddenOverflow`? Or barring that, what determines when text and block content will be considered overflow?

**Comment by felixmariotto** [comment]
Hi !

Sorry fore the late answer, I was busy this weekend..
You fiddle doesn't work because you didn't enable clipping ( three.js wants you to [manually enable it](https://threejs.org/docs/?q=renderer#api/en/renderers/WebGLRenderer.localClippingEnabled) for performance reasons, like shadowmaps ).
See this corrected fiddle : https://jsfiddle.net/felixmariotto/x63aonrs/
Line 18 : `renderer.localClippingEnabled = true;`

I will add a comment in the example and update the doc because I agree that's easy to forget.

**Comment by felixmariotto** [comment]
Added a comment : 
https://github.com/felixmariotto/three-mesh-ui/blob/77880a66136a92b0623de10d4d6fabb092e2267b/examples/hidden_overflow.js#L85-L87
And a warning in the docs : https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#list-of-attributes
